---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.10
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[m4::default]
    attributes:
